# Generated by Django 4.2.1 on 2023-06-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='Title',
            new_name='BillNo',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='Content',
            new_name='Remark',
        ),
        migrations.AddField(
            model_name='notes',
            name='AcceptReject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='ActualPaymentDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='BillDate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='BillValue',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='GivenPaymentDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='MIRONo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='NameofSupplier',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='PONo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='QtyinMT',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='ReceivedOn',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='Species',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
