# Generated by Django 4.2.1 on 2023-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0002_rename_title_notes_billno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='ActualPaymentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='BillDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='GivenPaymentDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='ReceivedOn',
            field=models.DateTimeField(null=True),
        ),
    ]
