# Generated by Django 4.2.1 on 2023-06-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0003_alter_notes_actualpaymentdate_alter_notes_billdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='ActualPaymentDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='BillDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='CreationDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='GivenPaymentDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='ReceivedOn',
            field=models.DateField(null=True),
        ),
    ]
