# Generated by Django 4.2.1 on 2023-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0004_alter_notes_actualpaymentdate_alter_notes_billdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='CreationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
