# Generated by Django 4.2.1 on 2023-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enotes', '0005_alter_notes_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='ActualPaymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='BillDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='GivenPaymentDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='ReceivedOn',
            field=models.DateField(blank=True, null=True),
        ),
    ]
